variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
  - build

jib-build:
  stage: build
  image: openjdk:11-jdk
  tags:
    - xlek
  script:
    - ./mvnw compile jib:build
      -Dmaven.repo.local=.m2/repository
      -Djib.to.auth.username=$CI_REGISTRY_USER
      -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
